# Generated by Django 3.1.7 on 2021-04-07 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('numMotorcycleSpots', models.IntegerField(default=0)),
                ('numCarSpots', models.IntegerField(default=0)),
                ('numOversizeSpots', models.IntegerField(default=0)),
                ('motorcycleSpotPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('carSpotPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('oversizeSpotPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLotEventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanceFromEvent', models.DecimalField(decimal_places=1, max_digits=6)),
                ('availableMotorcycleSpots', models.IntegerField()),
                ('availableCarSpots', models.IntegerField()),
                ('availableOversizeSpots', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.event')),
                ('parkingLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('isSupervisor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotType', models.CharField(max_length=1)),
                ('parkingLotEventData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingloteventdata')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
