# Generated by Django 3.1.6 on 2021-03-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('eventDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceCode', models.CharField(max_length=50)),
                ('parkingLotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transDate', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.event')),
                ('parkingSpotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transTypeName', models.CharField(max_length=20)),
                ('transHistoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.transactionhistory')),
            ],
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.user'),
        ),
        migrations.CreateModel(
            name='ParkingSpotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20)),
                ('parkingSpotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpotHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentStartDate', models.DateTimeField()),
                ('rentEndDate', models.DateTimeField()),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingspot')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.user'),
        ),
    ]
