# Generated by Django 3.1.6 on 2021-03-02 22:24

from django.db import migrations
from django.utils import timezone

def populate_db(apps, schema_editor):

    User = django.auth.models.User

    user = User(username="SystemTest", password="systest", firstName="System", lastName="Test", phoneNumber="0000000000")

    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
